In [1]:
import numpy as np

In [2]:
points = np.concatenate([np.random.normal(size=(15,3)),np.ones((15,1))],axis=1)
rep_points=np.repeat(points[np.newaxis],axis=0,repeats=100)

transf_mat = np.concatenate([np.concatenate([np.eye(3),np.zeros((1,3))]),np.array([4,4,4,1])[:,np.newaxis]],axis=1)
#transf_mat[np.newaxis,:,:]
rep_mat=np.repeat(transf_mat[np.newaxis,:,:],repeats=10,axis=0)
#points
rep_points[0]
#rep_mat.shape

array([[ 0.87478566, -0.60553192,  1.60916853,  1.        ],
       [-1.40721946,  1.17739769, -0.78552252,  1.        ],
       [-0.54817872, -0.783734  , -0.35009213,  1.        ],
       [ 2.00103761, -1.05377519, -0.54026551,  1.        ],
       [ 0.67055105, -0.04489325,  1.09106315,  1.        ],
       [ 0.08481855,  1.47286326,  0.04269896,  1.        ],
       [ 0.44152641,  1.19360206,  1.37923605,  1.        ],
       [ 0.03962717,  0.20059932,  1.33515822,  1.        ],
       [-0.21592328, -0.23942643,  0.21001405,  1.        ],
       [-0.22875983,  0.85766134, -0.81366667,  1.        ],
       [-0.88204181, -2.50117542, -0.25425551,  1.        ],
       [ 0.37109585,  0.89207891, -0.61975605,  1.        ],
       [ 0.88013743,  0.0453521 ,  0.27790605,  1.        ],
       [ 0.97210731,  1.52709723, -1.66072416,  1.        ],
       [ 1.01787219, -0.87032011,  0.32351256,  1.        ]])

In [3]:
repetitions=10
samples = 100
samples = np.concatenate([np.random.normal(size=(samples,15,3)),np.ones((samples,15,1))],axis=2).transpose((0,2,1))[:,np.newaxis,:,:]
temp = np.repeat(np.concatenate([np.zeros((1,3)),np.ones((1,1))],axis=1)[np.newaxis,:,:],axis=0,repeats=repetitions)
T_mat = np.concatenate([np.random.normal(size=(repetitions,3,4)),temp],axis=1)
samples.shape

(100, 1, 4, 15)

In [4]:
np.matmul(T_mat,points.T)[0,0:3,:]#[0][:,:].T

array([[ 0.80832282,  0.60803877, -0.05491669,  3.19589685,  1.28264541,
         2.31617461,  1.78370569,  0.50277588,  0.48062183,  1.92306157,
        -1.89620116,  2.62507594,  2.10497289,  4.52237957,  1.54154976],
       [ 2.17385311, -0.90252656, -0.30988504,  3.05291963,  1.96773338,
         1.44876995,  2.15804226,  1.24523447,  0.47164159,  0.59753687,
        -1.35132626,  1.48006803,  2.09438156,  2.28253405,  1.97171345],
       [ 2.57284512,  0.56173904,  0.69940469,  0.45436286,  2.15849042,
         1.37418884,  2.60407519,  2.43098837,  1.30306585,  0.47875115,
         0.55991736,  0.66155023,  1.39479509, -0.24879977,  1.31182708]])

In [22]:
#np.tensordot(rep_mat[:,:,:],rep_points.transpose((0,2,1))[:,:,:],axes=([1,1])).transpose((2,0,1,3)).shape
#layer_result = np.matmul(T_mat,samples)#axes=([1,1])).shape#.transpose((2,0,1,3)).shape
layer_result = np.tensordot(T_mat,samples,axes=[[1,2]])

layer_result.shape

ValueError: not enough values to unpack (expected 2, got 1)

In [83]:
rep_points.transpose((0,2,1)).shape

(100, 4, 15)

In [108]:
layer_result[0,0].T-4

array([[-0.37640205,  0.34691539, -0.40167507, -3.        ],
       [-0.27322468,  0.23534353, -0.21785809, -3.        ],
       [-1.06404813, -0.17937243,  1.02569003, -3.        ],
       [ 0.35740938,  0.28563662,  0.6069245 , -3.        ],
       [-0.19160529,  1.64992979,  0.85130447, -3.        ],
       [ 0.11906093,  0.22656302,  0.61884062, -3.        ],
       [-0.51601906, -1.82783493,  0.66236633, -3.        ],
       [-0.81697294,  2.34147576, -0.09579775, -3.        ],
       [-0.44507135, -0.26065803,  2.20832778, -3.        ],
       [ 1.5765807 ,  0.20440062,  2.08144774, -3.        ],
       [ 1.22495748,  0.139491  ,  0.13754735, -3.        ],
       [-0.85743498,  0.88310601, -0.58835394, -3.        ],
       [-1.34536058,  0.89734811,  0.75407224, -3.        ],
       [-0.38171783,  0.66475677, -0.75329302, -3.        ],
       [ 0.79998754,  0.22431895,  1.27852695, -3.        ]])